#!/bin/bash

set -euo pipefail

DIR=${1-}

if [ -z "$DIR" ]; then
	exec tmux list-sessions
fi

if [ -d "$DIR" ]; then
	DIR=$(cd $DIR; pwd)
	NAME=$(basename "$DIR")
else
	NAME=$DIR
fi

NAME=$(tr -- '-.' _ <<< "$NAME")

if [ -d "$DIR" ]; then
	exec tmux new-session -A -c "$DIR" -s "$NAME"
fi

tmux attach-session -t "$NAME"
