#!/bin/bash

attach() {
  tmux attach-session -t ${1:-$name}
}

list() {
  tmux list-session ${1:+"-F#{session_name}"}
}

exact_match() {
  list short | grep --quiet -x $name && attach
}

# one match, use it
# two matches, error out
close_match() {
  matches=($(list short | grep $name))

  case ${#matches[*]} in
    0) # no match
      return
      ;;
    1) # closest match
      attach $matches
      ;;
    *)
      # disambiguate
      list | grep $name
      exit
      ;;
  esac
}

new() {
  tmux new-session -s $name "$@"
}

name=$1
shift

if [ -z "$name" ]; then
  list
  exit
fi

# $name is a valid directory, go to it and start tmux
if [ -d "$name" ]; then
  cd $name
  name=`basename $PWD`
fi

exact_match || close_match || new "$@"
