#!/bin/bash

attach() {
  tmux attach-session -t ${1:-$name}
}

list() {
  if [[ "$1" == 'short' ]]; then
    local args='-F #{session_name}'
    shift
  fi

  tmux list-session $args | grep "$@" "${name:-$}"
}

exact_match() {
  list short --quiet -x && attach
}

# no match, create new
# one match, use it
# two matches, show options
close_match() {
  matches=( $(list short) )

  case ${#matches[*]} in
    0) # no match
      return
      ;;
    1) # closest match
      attach $matches
      ;;
    *)
      # disambiguate
      list
      ;;
  esac
}

new() {
  tmux new-session -s $name "$@"
}

name=$1
shift

if [ -z "$name" ]; then
  list
  exit
fi

# $name is a valid directory, go to it and start tmux
if [ -d "$name" ]; then
  cd $name
  name=`basename $PWD`
fi

exact_match || close_match || new "$@"
